# mkdocs.yml

site_name: ResumeParser Pro
site_url: https://Ruthikr.github.io/ai-resume-parser/
repo_url: https://github.com/Ruthikr/ai-resume-parser
repo_name: Ruthikr/ai-resume-parser

theme:
  name: material
  logo: assets/logo.png  # Optional: Add a logo image in docs/assets/
  favicon: assets/logo.png # Optional
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# This tells MkDocs where to find your documentation files
nav:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Quickstart': 'quickstart.md'
  - 'API Reference': 'api_reference.md'
